"""Adds version column to RunArtifact

Revision ID: 075ece72a4c0
Revises: 4b36340ee99f
Create Date: 2026-02-23 13:22:28.615145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075ece72a4c0'
down_revision: Union[str, None] = '4b36340ee99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_artifact', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_artifact', 'version')
    # ### end Alembic commands ###
