"""Adds reporting_data column to run_artifact table

Revision ID: 0b04e89975a5
Revises: 2d49072df8f1
Create Date: 2026-01-30 10:08:48.616025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b04e89975a5'
down_revision: Union[str, None] = '2d49072df8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_artifact', sa.Column('reporting_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_artifact', 'reporting_data')
    # ### end Alembic commands ###
