"""Adds table ComplianceFinalisationRecord

Revision ID: 14be216200d7
Revises: 97983bab48cb
Create Date: 2026-06-16 07:44:12.909086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14be216200d7'
down_revision: Union[str, None] = '97983bab48cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_finalisation_record',
    sa.Column('compliance_request_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['compliance_request_id'], ['compliance_request.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user_.id'], ),
    sa.PrimaryKeyConstraint('compliance_request_id'),
    sa.UniqueConstraint('compliance_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_finalisation_record')
    # ### end Alembic commands ###
