"""add playlist support to runs

Revision ID: 172f0f9f0b85
Revises: a232a79c72df
Create Date: 2026-01-09 14:13:45.936584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "172f0f9f0b85"
down_revision: Union[str, None] = "a232a79c72df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run", sa.Column("playlist_execution_id", sa.String(), nullable=True))
    op.add_column("run", sa.Column("playlist_order", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_run_playlist_execution_id"), "run", ["playlist_execution_id"], unique=False)
    op.create_index(
        "run_playlist_execution_id_order_idx", "run", ["playlist_execution_id", "playlist_order"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("run_playlist_execution_id_order_idx", table_name="run")
    op.drop_index(op.f("ix_run_playlist_execution_id"), table_name="run")
    op.drop_column("run", "playlist_order")
    op.drop_column("run", "playlist_execution_id")
    # ### end Alembic commands ###
