"""Adds Run Report Generation table

Revision ID: 1b884d034a4c
Revises: 0b04e89975a5
Create Date: 2026-02-03 15:23:23.175831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b884d034a4c'
down_revision: Union[str, None] = '0b04e89975a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_report_generation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_artifact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_artifact_id'], ['run_artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_report_generation')
    # ### end Alembic commands ###
