"""Adds ComplianceRequestFinalisation table

Revision ID: 24c45d66609b
Revises: 63667f661ad5
Create Date: 2026-06-30 13:37:57.968436

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24c45d66609b'
down_revision: str | None = '63667f661ad5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_request_finalisation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compliance_request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_request_id'], ['compliance_request.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('compliance_request', 'file_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_request', sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_table('compliance_request_finalisation')
    # ### end Alembic commands ###
