"""added_sub_domain

Revision ID: 37fc7586cba8
Revises: a6b36899fa4d
Create Date: 2025-06-05 17:29:22.780655

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37fc7586cba8"
down_revision: Union[str, None] = "a6b36899fa4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_", sa.Column("subscription_domain", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_", "subscription_domain")
    # ### end Alembic commands ###
