"""add_static_uri

Revision ID: 49a5dd29ff0b
Revises: 37fc7586cba8
Create Date: 2025-07-10 20:17:32.709608

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49a5dd29ff0b"
down_revision: Union[str, None] = "37fc7586cba8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_teststack_id"), table_name="run")
    op.create_index(op.f("ix_run_teststack_id"), "run", ["teststack_id"], unique=False)
    op.create_index("user_id_run_status_idx", "run", ["user_id", "run_status"], unique=False)
    op.add_column("user_", sa.Column("is_static_uri", sa.BOOLEAN(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_", "is_static_uri")
    op.drop_index("user_id_run_status_idx", table_name="run")
    op.drop_index(op.f("ix_run_teststack_id"), table_name="run")
    op.create_index(op.f("ix_run_teststack_id"), "run", ["teststack_id"], unique=True)
    # ### end Alembic commands ###
