"""static_uri_rungroup

Revision ID: 4bc8586aa906
Revises: 97983bab48cb
Create Date: 2026-06-11 16:34:49.524098

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bc8586aa906"
down_revision: Union[str, None] = "97983bab48cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run", sa.Column("pod_name", sa.String(), nullable=True))
    op.drop_index(op.f("ix_run_teststack_id"), table_name="run")
    op.create_index(op.f("ix_run_pod_name"), "run", ["pod_name"], unique=False)
    op.drop_column("run", "teststack_id")
    op.add_column(
        "run_group", sa.Column("is_static_uri", sa.BOOLEAN(), nullable=False, server_default=sa.text("false"))
    )
    op.alter_column("run_group", "is_static_uri", server_default=None)

    # Migrate is_static_uri on the User and apply it to the new RunGroup specific value
    op.execute("""UPDATE run_group rg
SET is_static_uri = u.is_static_uri
FROM "user_" u
WHERE rg.user_id = u.id;""")

    op.drop_column("user_", "is_static_uri")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_",
        sa.Column("is_static_uri", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    )
    op.drop_column("run_group", "is_static_uri")
    op.add_column("run", sa.Column("teststack_id", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_run_pod_name"), table_name="run")
    op.create_index(op.f("ix_run_teststack_id"), "run", ["teststack_id"], unique=False)
    op.drop_column("run", "pod_name")
    # ### end Alembic commands ###
