"""file_store_migration_finish

Revision ID: 50ac28df13fa
Revises: 9a420fd21b53
Create Date: 2026-08-27 11:25:44.176876

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50ac28df13fa"
down_revision: str | None = "9a420fd21b53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_run_artifact_migrated"), table_name="run")
    op.drop_constraint(op.f("run_run_artifact_id_fkey"), "run", type_="foreignkey")
    op.drop_column("run", "run_artifact_id")
    op.drop_column("run", "run_artifact_migrated_error")
    op.drop_column("run", "run_artifact_migrated")

    op.drop_table("run_artifact")
    op.drop_index(op.f("ix_compliance_record_file_data_migrated"), table_name="compliance_record")
    op.drop_table("compliance_record")
    op.drop_index(
        op.f("ix_compliance_request_finalisation_file_data_migrated"), table_name="compliance_request_finalisation"
    )
    op.drop_column("compliance_request_finalisation", "file_data")
    op.drop_column("compliance_request_finalisation", "file_data_migrated_error")
    op.drop_column("compliance_request_finalisation", "file_data_migrated")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "run",
        sa.Column(
            "run_artifact_migrated", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False
        ),
    )
    op.add_column("run", sa.Column("run_artifact_migrated_error", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("run", sa.Column("run_artifact_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("run_run_artifact_id_fkey"), "run", "run_artifact", ["run_artifact_id"], ["id"])
    op.create_index(op.f("ix_run_run_artifact_migrated"), "run", ["run_artifact_migrated"], unique=False)
    op.add_column(
        "compliance_request_finalisation",
        sa.Column(
            "file_data_migrated", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "compliance_request_finalisation",
        sa.Column("file_data_migrated_error", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "compliance_request_finalisation",
        sa.Column("file_data", postgresql.BYTEA(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_compliance_request_finalisation_file_data_migrated"),
        "compliance_request_finalisation",
        ["file_data_migrated"],
        unique=False,
    )
    op.create_table(
        "compliance_record",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("run_group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("requester_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("file_data", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column(
            "file_data_migrated", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False
        ),
        sa.Column("file_data_migrated_error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["requester_id"], ["user_.id"], name=op.f("compliance_record_requester_id_fkey")),
        sa.ForeignKeyConstraint(["run_group_id"], ["run_group.id"], name=op.f("compliance_record_run_group_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("compliance_record_pkey")),
    )
    op.create_index(
        op.f("ix_compliance_record_file_data_migrated"), "compliance_record", ["file_data_migrated"], unique=False
    )
    op.create_table(
        "run_artifact",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("compression", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("file_data", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column("reporting_data", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("run_artifact_pkey")),
    )
    # ### end Alembic commands ###
