"""Add user_name to User table

Revision ID: 567e2d898a5b
Revises: ba8b8716c58e
Create Date: 2025-09-12 13:02:36.565979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567e2d898a5b'
down_revision: Union[str, None] = 'ba8b8716c58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_', 'user_name')
    # ### end Alembic commands ###
