"""add_device_cert

Revision ID: 5b8e7f27f1cf
Revises: 4e0791b908bd
Create Date: 2025-07-21 13:42:14.841322

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b8e7f27f1cf"
down_revision: Union[str, None] = "4e0791b908bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_", "certificate_x509_der", new_column_name="aggregator_certificate_x509_der", nullable=True)
    op.alter_column(
        "user_", "certificate_p12_bundle", new_column_name="aggregator_certificate_p12_bundle", nullable=True
    )
    op.add_column("user_", sa.Column("device_certificate_p12_bundle", sa.LargeBinary(), nullable=True))
    op.add_column("user_", sa.Column("device_certificate_x509_der", sa.LargeBinary(), nullable=True))
    op.add_column("user_", sa.Column("is_device_cert", sa.BOOLEAN(), nullable=False, server_default="0"))

    op.add_column("run", sa.Column("is_device_cert", sa.BOOLEAN(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("run", "is_device_cert")

    op.drop_column("user_", "is_device_cert")
    op.drop_column("user_", "device_certificate_x509_der")
    op.drop_column("user_", "device_certificate_p12_bundle")
    op.alter_column("user_", "aggregator_certificate_x509_der", new_column_name="certificate_x509_der", nullable=False)
    op.alter_column(
        "user_", "aggregator_certificate_p12_bundle", new_column_name="certificate_p12_bundle", nullable=False
    )
    # ### end Alembic commands ###
