"""empty message

Revision ID: 5df195a5d626
Revises:
Create Date: 2025-03-26 16:34:25.900105

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5df195a5d626"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_artifact",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("compression", sa.String(), nullable=False),
        sa.Column("file_data", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject_id", sa.String(), nullable=False),
        sa.Column("issuer_id", sa.String(), nullable=False),
        sa.Column("certificate_p12_bundle", sa.LargeBinary(), nullable=False),
        sa.Column("certificate_x509_der", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "issuer_id", name="subject_id_issuer_id_key"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("teststack_id", sa.String(), nullable=False),
        sa.Column("testprocedure_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finalised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finalisation_status", sa.Integer(), nullable=False),
        sa.Column("run_artifact_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_artifact_id"],
            ["run_artifact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "finalisation_status_created_at_testprocedure_id_idx",
        "run",
        ["finalisation_status", "created_at", "testprocedure_id"],
        unique=False,
    )
    op.create_index(op.f("ix_run_teststack_id"), "run", ["teststack_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_teststack_id"), table_name="run")
    op.drop_index("finalisation_status_created_at_testprocedure_id_idx", table_name="run")
    op.drop_table("run")
    op.drop_table("user_")
    op.drop_table("run_artifact")
    # ### end Alembic commands ###
