"""Add file_data column to ComplianceRequest table

Revision ID: 63667f661ad5
Revises: 97983bab48cb
Create Date: 2026-06-17 11:50:45.135370

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '63667f661ad5'
down_revision: str | None = '97983bab48cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_request', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_request', 'file_data')
    # ### end Alembic commands ###
