"""compliance_requests

Revision ID: 97983bab48cb
Revises: 075ece72a4c0
Create Date: 2026-05-27 11:46:27.495680

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97983bab48cb"
down_revision: str | None = "075ece72a4c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("csip_aus_version", sa.String(), nullable=False),
        sa.Column("witnessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("der_brand", sa.String(), nullable=False),
        sa.Column("der_oem", sa.String(), nullable=False),
        sa.Column("der_series", sa.String(), nullable=False),
        sa.Column("der_representative_models", sa.String(), nullable=False),
        sa.Column("software_client_type", sa.String(), nullable=False),
        sa.Column("software_client_providers", sa.String(), nullable=False),
        sa.Column("software_client_versions", sa.String(), nullable=False),
        sa.Column("onsite_hardware_details", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["user_.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "compliance_request_class",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("compliance_request_id", sa.Integer(), nullable=False),
        sa.Column("compliance_class", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["compliance_request_id"],
            ["compliance_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "compliance_request_run",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("compliance_request_id", sa.Integer(), nullable=False),
        sa.Column("compliance_run_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["compliance_request_id"],
            ["compliance_request.id"],
        ),
        sa.ForeignKeyConstraint(
            ["compliance_run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("compliance_request_run")
    op.drop_table("compliance_request_class")
    op.drop_table("compliance_request")
    # ### end Alembic commands ###
