"""file_store_migration_start

Revision ID: 9a420fd21b53
Revises: ab03a5b33836
Create Date: 2026-08-21 15:26:46.501133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a420fd21b53"
down_revision: str | None = "ab03a5b33836"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_report_generation")
    op.add_column(
        "compliance_record", sa.Column("file_data_migrated", sa.BOOLEAN(), server_default="0", nullable=False)
    )
    op.add_column("compliance_record", sa.Column("file_data_migrated_error", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_compliance_record_file_data_migrated"), "compliance_record", ["file_data_migrated"], unique=False
    )
    op.add_column(
        "compliance_request_finalisation",
        sa.Column("file_data_migrated", sa.BOOLEAN(), server_default="0", nullable=False),
    )
    op.add_column("compliance_request_finalisation", sa.Column("file_data_migrated_error", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_compliance_request_finalisation_file_data_migrated"),
        "compliance_request_finalisation",
        ["file_data_migrated"],
        unique=False,
    )
    op.add_column("run", sa.Column("run_artifact_migrated", sa.BOOLEAN(), server_default="0", nullable=False))
    op.add_column("run", sa.Column("run_artifact_migrated_error", sa.String(), nullable=True))
    op.create_index(op.f("ix_run_run_artifact_migrated"), "run", ["run_artifact_migrated"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_run_artifact_migrated"), table_name="run")
    op.drop_column("run", "run_artifact_migrated_error")
    op.drop_column("run", "run_artifact_migrated")
    op.drop_index(
        op.f("ix_compliance_request_finalisation_file_data_migrated"), table_name="compliance_request_finalisation"
    )
    op.drop_column("compliance_request_finalisation", "file_data_migrated_error")
    op.drop_column("compliance_request_finalisation", "file_data_migrated")
    op.drop_index(op.f("ix_compliance_record_file_data_migrated"), table_name="compliance_record")
    op.drop_column("compliance_record", "file_data_migrated_error")
    op.drop_column("compliance_record", "file_data_migrated")
    op.create_table(
        "run_report_generation",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("run_artifact_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_artifact_id"], ["run_artifact.id"], name=op.f("run_report_generation_run_artifact_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("run_report_generation_pkey")),
    )
    # ### end Alembic commands ###
