"""Adds file_data col to compliance record

Revision ID: a232a79c72df
Revises: b079d331af6e
Create Date: 2025-11-25 13:48:14.435869

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a232a79c72df"
down_revision: str | None = "b079d331af6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("compliance_record", sa.Column("file_data", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("compliance_record", "file_data")
    # ### end Alembic commands ###
