"""empty message

Revision ID: a6b36899fa4d
Revises: 5df195a5d626
Create Date: 2025-06-04 09:59:26.462691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b36899fa4d'
down_revision: Union[str, None] = '5df195a5d626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('run_status', sa.Integer(), nullable=False))
    op.drop_index('finalisation_status_created_at_testprocedure_id_idx', table_name='run')
    op.create_index('run_status_created_at_testprocedure_id_idx', 'run', ['run_status', 'created_at', 'testprocedure_id'], unique=False)
    op.drop_column('run', 'finalisation_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('finalisation_status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('run_status_created_at_testprocedure_id_idx', table_name='run')
    op.create_index('finalisation_status_created_at_testprocedure_id_idx', 'run', ['finalisation_status', 'created_at', 'testprocedure_id'], unique=False)
    op.drop_column('run', 'run_status')
    # ### end Alembic commands ###
