"""Modify/Add columns of ComplianceRequest table

Revision ID: ab03a5b33836
Revises: fa77cc530a1d
Create Date: 2026-08-17 09:55:22.346089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab03a5b33836"
down_revision: Union[str, None] = "fa77cc530a1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("compliance_request", sa.Column("cactus_version", sa.String(), nullable=False))
    op.add_column("compliance_request", sa.Column("der_cec_listed_models", sa.String(), nullable=False))
    op.add_column("compliance_request", sa.Column("der_unlisted_models", sa.String(), nullable=False))
    op.add_column("compliance_request", sa.Column("der_white_labelled_models", sa.String(), nullable=False))
    op.add_column("compliance_request", sa.Column("software_client_name", sa.String(), nullable=False))
    op.drop_column("compliance_request", "software_client_providers")
    op.drop_column("compliance_request", "der_representative_models")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "compliance_request", sa.Column("der_representative_models", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "compliance_request", sa.Column("software_client_providers", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("compliance_request", "software_client_name")
    op.drop_column("compliance_request", "der_white_labelled_models")
    op.drop_column("compliance_request", "der_unlisted_models")
    op.drop_column("compliance_request", "der_cec_listed_models")
    op.drop_column("compliance_request", "cactus_version")
    # ### end Alembic commands ###
