"""Adds compliance record table

Revision ID: b079d331af6e
Revises: de92d2df4173
Create Date: 2025-11-20 11:15:32.203726

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b079d331af6e"
down_revision: Union[str, None] = "de92d2df4173"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_group_id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["user_.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_group_id"],
            ["run_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("compliance_record")
    # ### end Alembic commands ###
