"""Adds PEM to User Table

Revision ID: ba8b8716c58e
Revises: bac93a96c47d
Create Date: 2025-08-29 12:15:07.310222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ba8b8716c58e"
down_revision: Union[str, None] = "bac93a96c47d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_", sa.Column("aggregator_certificate_pem", sa.LargeBinary(), nullable=True))
    op.add_column("user_", sa.Column("aggregator_certificate_pem_key", sa.LargeBinary(), nullable=True))
    op.add_column("user_", sa.Column("device_certificate_pem", sa.LargeBinary(), nullable=True))
    op.add_column("user_", sa.Column("device_certificate_pem_key", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_", "device_certificate_pem_key")
    op.drop_column("user_", "device_certificate_pem")
    op.drop_column("user_", "aggregator_certificate_pem_key")
    op.drop_column("user_", "aggregator_certificate_pem")
    # ### end Alembic commands ###
