"""add_pen

Revision ID: bac93a96c47d
Revises: 415f3cef09cb
Create Date: 2025-08-19 15:22:18.253977

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bac93a96c47d"
down_revision: Union[str, None] = "415f3cef09cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_", sa.Column("pen", sa.Integer(), nullable=False, server_default="0"))
    op.alter_column("user_", "pen", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_", "pen")
    # ### end Alembic commands ###
