"""add_rungroup_certs

Revision ID: de92d2df4173
Revises: 567e2d898a5b
Create Date: 2025-11-07 13:55:25.381965

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de92d2df4173"
down_revision: Union[str, None] = "567e2d898a5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run_group", sa.Column("is_device_cert", sa.BOOLEAN(), nullable=True))
    op.add_column("run_group", sa.Column("certificate_pem", sa.LargeBinary(), nullable=True))
    op.add_column("run_group", sa.Column("certificate_generated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("run_group", sa.Column("certificate_id", sa.Integer(), nullable=False, server_default="0"))
    op.drop_column("user_", "device_certificate_x509_der")
    op.drop_column("user_", "aggregator_certificate_pem")
    op.drop_column("user_", "is_device_cert")
    op.drop_column("user_", "aggregator_certificate_pem_key")
    op.drop_column("user_", "device_certificate_pem_key")
    op.drop_column("user_", "device_certificate_p12_bundle")
    op.drop_column("user_", "aggregator_certificate_x509_der")
    op.drop_column("user_", "aggregator_certificate_p12_bundle")
    op.drop_column("user_", "device_certificate_pem")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_", sa.Column("device_certificate_pem", postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column(
        "user_", sa.Column("aggregator_certificate_p12_bundle", postgresql.BYTEA(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user_", sa.Column("aggregator_certificate_x509_der", postgresql.BYTEA(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user_", sa.Column("device_certificate_p12_bundle", postgresql.BYTEA(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user_", sa.Column("device_certificate_pem_key", postgresql.BYTEA(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user_", sa.Column("aggregator_certificate_pem_key", postgresql.BYTEA(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user_",
        sa.Column("is_device_cert", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_", sa.Column("aggregator_certificate_pem", postgresql.BYTEA(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user_", sa.Column("device_certificate_x509_der", postgresql.BYTEA(), autoincrement=False, nullable=True)
    )
    op.drop_column("run_group", "certificate_id")
    op.drop_column("run_group", "certificate_generated_at")
    op.drop_column("run_group", "certificate_pem")
    op.drop_column("run_group", "is_device_cert")
    # ### end Alembic commands ###
