"""add deploy_release

Revision ID: fa77cc530a1d
Revises: 3cfee29820b0
Create Date: 2026-08-04 10:12:33.104512

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa77cc530a1d"
down_revision: str | None = "3cfee29820b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deploy_release",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("release_tag", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deploy_release")
    # ### end Alembic commands ###
