# Management Pod
apiVersion: v1
kind: Pod
metadata:
  name: management
  labels:
    app: management
spec:
  serviceAccountName: pod-creator
  containers:
    - name: environment
      image: ${ORCHESTRATOR_K8S_MANAGER_IMAGE}
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      env:
        - name: TESTING_FQDN
          value: ${TESTING_FQDN}
        - name: ORCHESTRATOR_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orchestrator-db-secret
              key: ORCHESTRATOR_DATABASE_URL
---
# TODO: Still unsure how this will be exposed
# Service to expose the management API
apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  selector:
    app: management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32080  # Expose on host
  type: NodePort
